routes/web.php
<?php

Route::get(
    '/',
    function () {
        return view('layout');
    }
);

Route::get('/mesas', 'MesaController@index')->name('mesas.index');
Route::get('/mesas/increment', 'MesaController@increment')->name('mesas.increment');
Route::get('/mesas/decrement', 'MesaController@decrement')->name('mesas.decrement');
Route::get('/pedido/{mesa}/create', 'PedidoController@create')->name('pedido.create');
Route::get('/mesas/{id}', 'MesaController@update')->name('mesas.index');
Route::get('/pedido/{mesa}/editar', 'PedidoController@editar')->name('pedido.edit');
Route::post('/pedido', 'PedidoController@save')->name('pedido.save');
Route::get('/pedido/{mesa}/edit', 'PedidoController@edit')->name('pedido.edit');
Route::put('/pedido/{mesa}', 'PedidoController@update')->name('pedido.update');
Route::post('/pedido', 'PedidoController@store')->name('pedido.store');

Route::group(
    ['prefix'=>'menu'],
    function () {
        Route::resource('productos', 'ProductoController');
    }
);

Route::group(
    ['prefix'=>'cocina'],
    function () {
        Route::get('pedidos', 'CocinaController@index')->name('pedidos.index');
        Route::post('pedidos/{idMesa}/{idProducto}', 'CocinaController@update')->name('pedidos.update');
    }
);

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $hidden = ['created_at', 'updated_at'];

    protected $fillable = ['nombre','categoria','descripcion','precio'];

    public function mesas()
    {
        return $this->belongsToMany('App\Mesa');
    }
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Producto;

class ProductoController extends Controller
{
    public function index()
    {
        $products = Producto::orderBy('nombre')->get();
        $productos_categorizados = $products->groupBy('categoria');
        return view('productos.index')->with('productos', $productos_categorizados);
    }

    public function create()
    {
        return view('productos.create');
    }

    public function store(Request $request)
    {
        $producto = new Producto($request->all());
        $producto->save();

        return redirect()->route('productos.index')
            ->with("info", "Su producto se registró exitosamente.")
            ->with("tab", $producto->categoria);
    }

    public function destroy(Producto $producto)
    {
        $tab = $producto->categoria;
        $producto->delete();
        return redirect()->route('productos.index')->with('tab', $tab);
    }

    public function edit($id)
    {
        $producto = Producto::find($id);
        return view('productos.edit')->with('producto', $producto);
    }

    public function update(Request $request, Producto $producto)
    {
        $producto->fill($request->all());
        if ($producto->isDirty()) {
            $producto->save();
            return redirect()->route('productos.index')
                ->with("info", "Su producto se actualizó exitosamente.")
                ->with("tab", $producto->categoria);
        }
        return redirect()->route('productos.index')->with("tab", $producto->categoria);
    }
}

resources/views/productos/create.blade.php
@extends('layout')
@section('content')

<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-md-6 offset-3">
            <div class="card">
                <h3 class="card-header">
                    Registrar Producto
                </h3>
                <div class="card-body">
                    <form action="{{ route('productos.store') }}"
                          method="POST"
                          autocomplete="off">
                        @csrf
                        <div class="form-group">
                            <label for="name">Nombre del Producto</label>
                            <input id="name"
                                   class="form-control"
                                   type="text"
                                   name="nombre"
                                   pattern="[A-Za-z]* ?[A-Za-z]* ?[A-Za-z]* ?[A-Za-z]* ?"
                                   maxlength="100" required
                                   placeholder="Nombre Producto">
                        </div>
                        <div class="form-group">
                            <label for="category">Categoría del Producto</label>
                            <select name="categoria" class="form-control" id="category" required>
                                <option selected disabled>Elija una categoría</option>
                                <option value="bebidas" id="bebidas" >bebidas</option>
                                <option value="platos" id="platos">platos</option>
                                <option value="postres" id="postres">postres</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="description">Descripción del Producto</label>
                            <textarea class="form-control"
                                      name="descripcion"
                                      id="description"
                                      placeholder="Descripción Producto"
                                      maxlength="200"
                                      rows="6" required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="precio">Precio del Producto</label>
                            <input type="number"
                                   step=".01"
                                   min="1"
                                   class="form-control"
                                   name="precio" id="precio" placeholder="Precio Producto" required>
                        </div>
                        <div class="d-flex justify-content-center">
                          <button type="submit" class="btn btn-outline-warning">
                                <i class="fas fa-save"></i> Registrar
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/productos/edit.blade.php
@extends('layout')
@section('content')

<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-md-6 offset-3">
            <div class="card">
                <h3 class="card-header">
                    Editar Producto
                </h3>
                <div class="card-body">
                    <form action="{{route('productos.update', [$producto->id]) }}"
                          method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name">Nombre del Producto</label>
                            <input id="name"
                                   class="form-control"
                                   type="text"
                                   name="nombre"
                                   pattern="[A-Za-z]* ?[A-Za-z]* ?[A-Za-z]* ?[A-Za-z]* ?"
                                   maxlength="100" required
                                   placeholder="Nombre Producto"
                                   value= "{{ $producto->nombre }}" >
                        </div>
                        <div class="form-group">
                            <label for="category">Categoría del Producto</label>
                            <select name="categoria" class="form-control" id="category" required>

                              <option selected disabled>Elija una categoría</option>
                              @if($producto ->categoria == 'bebidas') {
                                <option value="bebidas" id="bebidas" selected="">bebidas</option>
                              @elseif($producto ->categoria == 'platos')
                               <option value="platos" id="platos" selected="">platos</option>
                              @else
                                <option value="postres" id="postres" selected="">postres</option>
                              @endif
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="description">Descripción del Producto</label>
                            <textarea class="form-control"
                                      name="descripcion"
                                      id="description"
                                      placeholder="Descripción Producto"
                                      maxlength="200"
                                      rows="6" required>{{ $producto->descripcion }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="precio">Precio del Producto</label>
                            <input type="number"
                                   step=".01"
                                   min="1"
                                   class="form-control"
                                   name="precio" id="precio" placeholder="Precio Producto" required
                                   value={{ $producto->precio }} >
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-outline-warning">
                                <i class="fas fa-save"></i> Actualizar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/productos/index.blade.php
@extends('layout')

@section('content')
    <style>
        .zoom {
            transition: transform .2s;
            margin: 0 auto;
        }

        .zoom:hover {
            transform: scale(0.97);
        }
    </style>
    <div class="container">
        <div class="row mt-3">
            <div class="col-12 col-md-10">
                @include('productos.productosLista')
            </div>
            <div class="col-12 col-md-2">
                <a class="btn btn-outline-warning"
                   href="{{action('ProductoController@create')}}">
                    <i class="fa fa-save"></i> Registrar Producto
                </a>
            </div>
        </div>
        <div class="modal" tabindex="-1" role="dialog" id="confirm_eliminar_modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Confirmando Eliminar Producto</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-12">
                                <div>¿Está seguro de eliminar el producto?</div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" id="modal-btn-si">Confirmar</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal" id="modal-btn-no">Cerrar</button>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            let tab = "{{ session('tab') ?? '' }}"
            if (tab) {
                $('#myTab a[href="#'+tab+'"]').tab('show')
            }
        })
    </script>
    <script>
        $('#confirm_eliminar_modal').on('shown.bs.modal', function (event) {
            $('#modal-btn-si').on('click', () => {
                event.relatedTarget.form.submit()
            });
        })

        $('#confirm_eliminar_modal').on('hide.bs.modal', function (event) {
            $('#modal-btn-si').off('click')
        })
    </script>
@endsection

resources/views/productos/producto.blade.php
<div class="col-12">
    <div class="card border-secondary mb-1 zoom">
        <div class="card-body text-secondary">
            <h5 class="card-title">{{ $producto->nombre }}</h5>
            <p class="card-text">{{ $producto->descripcion }}</p>
             <p class="card-text font-weight-bold">
                    Precio
                    <span class="badge badge-secondary">{{ $producto->precio }}</span>
            </p>
        </div>
        <div class="card-footer bg-transparent">
            <a href="{{action('ProductoController@edit',$producto->id)}}" class="btn btn-primary">
                <i class="fas fa-edit"></i> Editar
            </a>
            <form class="d-inline-flex" method="POST" action="{{ route('productos.destroy', [$producto->id])}}">
                @csrf
                @method('DELETE')
                <button type="button" class="btn btn-danger" data-toggle="modal"
                        data-target="#confirm_eliminar_modal">
                    <i class="fas fa-trash-alt"></i> Eliminar
                </button>
            </form>
        </div>
    </div>
</div>

resources/views/productos/productosLista.blade.php
<ul class="nav nav-tabs d-flex justify-content-center justify-content-md-around" id="myTab" role="tablist">
    <li class="nav-item w-25 text-center">
        <a class="nav-link active bg-dark text-white"
           id="bebidas-tab"
           data-toggle="tab"
           href="#bebidas"
           role="tab"
           aria-controls="bebidas"
           aria-selected="true">Bebidas</a>
    </li>
    <li class="nav-item w-25 text-center">
        <a class="nav-link bg-dark text-white"
           id="platos-tab"
           data-toggle="tab"
           href="#platos"
           role="tab"
           aria-controls="platos"
           aria-selected="false">Platos</a>
    </li>
    <li class="nav-item w-25 text-center">
        <a class="nav-link bg-dark text-white"
           id="postres-tab"
           data-toggle="tab"
           href="#postres"
           role="tab"
           aria-controls="postres"
           aria-selected="false">Postres</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade" id="postres" role="tabpanel" aria-labelledby="postres-tab">
        <div class="row">
            @if(!empty($productos['postres'])) 
                @foreach($productos['postres'] as $producto)
                    @include('productos.producto')
                @endforeach
            @else
                <div class="col">
                     <div class="alert alert-info" role="alert" id="alert">
                        <label>No existen productos en esta categoría.</label>
                    </div>
                </div>
            @endif
        </div>
    </div>
    <div class="tab-pane fade show active" id="bebidas" role="tabpanel" aria-labelledby="bebidas-tab">
        <div class="row">
            @if(!empty($productos['bebidas'])) 
                @foreach($productos['bebidas'] as $producto)
                    @include('productos.producto')
                @endforeach
            @else
            <div class="col">
                <div class="alert alert-info" role="alert" id="alert">
                    <label>No existen productos en esta categoría.</label>
                </div>  
            </div>
            @endif
        </div>
    </div>
    <div class="tab-pane fade" id="platos" role="tabpanel" aria-labelledby="platos-tab">
        <div class="row">
            @if(!empty($productos['platos'])) 
                @foreach($productos['platos'] as $producto)
                    @include('productos.producto')
                @endforeach
            @else
                <div class="col">
                     <div class="alert alert-info" role="alert" id="alert">
                        <label>No existen productos en esta categoría.</label>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>